### ISSUE TITLE
Edit Parent Search Results view styling is messed up if there are multiple matches

### ISSUE THREAD

**Issue by bffrost** [mcneilco/acas#338]
The controller is EditParentSearchResults_ParentListView

**Comment by fkmeyer** [comment]
<img width="724" alt="screen shot 2017-10-25 at 5 08 39 pm" src="https://user-images.githubusercontent.com/4369771/32029122-42a7538c-b9a7-11e7-9c80-3b246821229a.png">

**Comment by fkmeyer** [comment]
I made a duplicate ticket and linked the commit fix to that ticket. Closing this one.
