### ISSUE TITLE
When the location form field shows error style, the tree filter inout is also red

### ISSUE THREAD

**Issue by jmcneil86043** [mcneilco/acas#355]
The error styling that applies to the form field is also applied to the tree inouts when opened and should not be

**Comment by bffrost** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [When making a new lot aliquot entry, the location filter input is marked as required](https://trello.com/c/qIHaeuS9/175-when-making-a-new-lot-aliquot-entry-the-location-filter-input-is-marked-as-required)
