### ISSUE TITLE
SEL file loaded with Δ character in column header breaks

### ISSUE THREAD

**Issue by bffrost** [mcneilco/acas#55]
Proper result type with Δ does appear in value_kind table, however csv file generated by SEL contains unicode version <U+0394>
Roo hits a ConstraintViolation on tsvSave because the <U+0394> lsKind does not match anything in the value_kind table.

Appears to be a regression, but the cause is unknown.

**Comment by brianbolt** [comment]
This was fixed with mcneilco/acas-roo-server#145
